version: '3.7'

services:
  nodejs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: nodejs
    ports:
      - "3030:3030"
    depends_on:
            - webserver

  denojs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: denojs
    depends_on:
            - webserver

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
        - "80:80"