version: '3.7'

services:
  server1:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: server1
    ports:
      - "3030:3030"
    depends_on:
            - webserver

  server2:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: server2
    depends_on:
            - webserver

  server3:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: server3
    depends_on:
            - webserver

  server4:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: server4
    depends_on:
            - webserver

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./nginx/nginx_params.conf:/etc/nginx/nginx.conf"
    ports:
        - "80:80"