version: '3.7'

services:
  server-node:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: server-node
    ports:
      - "3030:3030"
    environment:
    - REDIS_URL=redis://redis
    links:
    - redis
    depends_on:
            - web-server

  rabbitmq:
    image: rabbitmq:management
    container_name: containerRabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    image: redis:latest
    container_name: redis
    expose:
            - 6379
    volumes:
      - ./data:/data

  web-server:
    image: nginx:mainline-alpine
    container_name: web-server
    volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./nginx/nginx_params.conf:/etc/nginx/nginx.conf"
    ports:
        - "80:80"

networks:
  default:
    driver: bridge
